# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cbo\PycharmProjects\SerialTerm\UI_SerialComDemo1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myMainWindow(object):
    def setupUi(self, myMainWindow):
        myMainWindow.setObjectName("myMainWindow")
        myMainWindow.resize(800, 600)
        myMainWindow.setWindowTitle("Serial COM Demo 1")
        myMainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(myMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_SerialPort = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_SerialPort.setGeometry(QtCore.QRect(620, 10, 170, 80))
        self.groupBox_SerialPort.setObjectName("groupBox_SerialPort")
        self.pushButton_SerialPort = QtWidgets.QPushButton(self.groupBox_SerialPort)
        self.pushButton_SerialPort.setGeometry(QtCore.QRect(20, 50, 130, 20))
        self.pushButton_SerialPort.setObjectName("pushButton_SerialPort")
        self.label_SerialPort = QtWidgets.QLabel(self.groupBox_SerialPort)
        self.label_SerialPort.setGeometry(QtCore.QRect(20, 20, 30, 20))
        self.label_SerialPort.setObjectName("label_SerialPort")
        self.comboBox_SerialPort = QtWidgets.QComboBox(self.groupBox_SerialPort)
        self.comboBox_SerialPort.setGeometry(QtCore.QRect(60, 20, 90, 20))
        self.comboBox_SerialPort.setObjectName("comboBox_SerialPort")
        self.groupBox_TRX = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_TRX.setEnabled(False)
        self.groupBox_TRX.setGeometry(QtCore.QRect(10, 10, 600, 530))
        self.groupBox_TRX.setObjectName("groupBox_TRX")
        self.textBrowser_TRX = QtWidgets.QTextBrowser(self.groupBox_TRX)
        self.textBrowser_TRX.setGeometry(QtCore.QRect(10, 20, 580, 430))
        self.textBrowser_TRX.setAcceptRichText(False)
        self.textBrowser_TRX.setObjectName("textBrowser_TRX")
        self.pushButton_TRX_Send = QtWidgets.QPushButton(self.groupBox_TRX)
        self.pushButton_TRX_Send.setGeometry(QtCore.QRect(440, 490, 70, 20))
        self.pushButton_TRX_Send.setObjectName("pushButton_TRX_Send")
        self.lineEdit_TRX = QtWidgets.QLineEdit(self.groupBox_TRX)
        self.lineEdit_TRX.setGeometry(QtCore.QRect(10, 490, 420, 20))
        self.lineEdit_TRX.setMaxLength(255)
        self.lineEdit_TRX.setObjectName("lineEdit_TRX")
        self.pushButton_TRX_Clr = QtWidgets.QPushButton(self.groupBox_TRX)
        self.pushButton_TRX_Clr.setGeometry(QtCore.QRect(440, 460, 150, 20))
        self.pushButton_TRX_Clr.setObjectName("pushButton_TRX_Clr")
        self.pushButton_TRX_Clr_2 = QtWidgets.QPushButton(self.groupBox_TRX)
        self.pushButton_TRX_Clr_2.setGeometry(QtCore.QRect(520, 490, 70, 20))
        self.pushButton_TRX_Clr_2.setObjectName("pushButton_TRX_Clr_2")
        myMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(myMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuABout = QtWidgets.QMenu(self.menubar)
        self.menuABout.setObjectName("menuABout")
        myMainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuABout.menuAction())

        self.retranslateUi(myMainWindow)
        self.pushButton_TRX_Send.clicked.connect(myMainWindow.btnSendTxtClicked)
        self.pushButton_TRX_Clr.clicked.connect(self.textBrowser_TRX.clear)
        self.pushButton_SerialPort.clicked.connect(myMainWindow.btnConnectClicked)
        self.pushButton_TRX_Clr_2.clicked.connect(self.lineEdit_TRX.clear)
        QtCore.QMetaObject.connectSlotsByName(myMainWindow)

    def retranslateUi(self, myMainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_SerialPort.setTitle(_translate("myMainWindow", "Serial Port"))
        self.pushButton_SerialPort.setText(_translate("myMainWindow", "Connect"))
        self.label_SerialPort.setText(_translate("myMainWindow", "Port: "))
        self.groupBox_TRX.setTitle(_translate("myMainWindow", "Serial Communication TX/RX"))
        self.pushButton_TRX_Send.setText(_translate("myMainWindow", "Send"))
        self.pushButton_TRX_Clr.setText(_translate("myMainWindow", "Clear Recv Data"))
        self.pushButton_TRX_Clr_2.setText(_translate("myMainWindow", "Clear Tx"))
        self.menuABout.setTitle(_translate("myMainWindow", "ABout"))
